# Log Levels: https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/Level.html

handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler

java.util.logging.ConsoleHandler.level.=ALL


# java.util.logging.ConsoleHandler.level = DEBUG
# java.util.logging.FileHandler.level = DEBUG
# org.yamcs.logging.level = DEBUG
# org.uniclogs.level = DEBUG


java.util.logging.FileHandler.formatter = org.yamcs.logging.CompactFormatter
java.util.logging.FileHandler.pattern = /var/log/yamcs/log
java.util.logging.FileHandler.limit = 20000000
java.util.logging.FileHandler.count = 50

org.uniclogs.formatter = org.yamcs.logging.CompactFormatter
org.uniclogs.pattern = /var/log/yamcs/log
org.uniclogs.limit = 20000000
org.uniclogs.count = 50